=== Rokli02/FRNJTJ_XMLGyak/FRNJTJ_0928/MR_ertodtd.dtd
<!ELEMENT model (A*, AB*, B*, C*)>
    <!ELEMENT A (Ab*, Ac)>
    <!ATTLIST A Aa ID #REQUIRED>
        <!ELEMENT Ab (Ax, Ay)> 
            <!ELEMENT Ax (#PCDATA)>
            <!ELEMENT Ay (#PCDATA)>
        <!ELEMENT Ac (Ad, Ae)>
            <!ELEMENT Ad (#PCDATA)>
            <!ELEMENT Ae (#PCDATA)>
    <!ELEMENT AB (ABc)>
    <!ATTLIST AB ABa IDREF #IMPLIED>
    <!ATTLIST AB ABb IDREF #IMPLIED>
        <!ELEMENT ABc (#PCDATA)>
        <!ELEMENT B (Bb)>
        <!ATTLIST B Ba ID #REQUIRED>
        <!ATTLIST B BC IDREF #IMPLIED>
            <!ELEMENT Bb (Bbx, Bby)>
                <!ELEMENT Bbx (#PCDATA)>
                <!ELEMENT Bby (#PCDATA)>
        <!ELEMENT C (Cb)>
        <!ATTLIST C Ca ID #REQUIRED>
            <!ELEMENT Cb (#PCDATA)>

=== Rokli02/FRNJTJ_XMLGyak/FRNJTJ_0928/MR_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE model SYSTEM "MR_ertodtd.dtd">

<model>
    <A Aa="og513">
        <Ab>
            <Ax>ax1</Ax>
            <Ay>ay1</Ay>
        </Ab>
        <Ab>
            <Ax>ax2</Ax>
            <Ay>ay2</Ay>
        </Ab>
        <Ac>
            <Ad>ad1</Ad>
            <Ae>ae1</Ae>
        </Ac>
    </A>
    <AB ABa="og513" ABb="og256">
        <ABc>abc1</ABc>
    </AB>
    <B Ba="og256" BC="og384">
        <Bb>
            <Bbx>bbx1</Bbx>
            <Bby>bby1</Bby>
        </Bb>
    </B>
    <C Ca="og384">
        <Cb>cb1</Cb>
    </C>
</model>
