=== Rokli02/FRNJTJ_XMLGyak/FRNJTJ_0928/MR_konyv.dtd
<?xml version="1.0" encoding="UTF-8"?>
       <!ELEMENT konyvek (konyv*)>
           <!ELEMENT konyv (cim, kiadas, kiado, szerzo+, abstract?)>
           <!ATTLIST konyv id ID #REQUIRED>
                <!ELEMENT cim (#PCDATA)>
                <!ELEMENT kiadas (#PCDATA)>
                <!ELEMENT kiado (#PCDATA)>
                <!ELEMENT szerzo (#PCDATA)>
                <!ELEMENT abstract (#PCDATA)>

=== Rokli02/FRNJTJ_XMLGyak/FRNJTJ_0928/MR_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE konyvek SYSTEM "MR_konyv.dtd">

<konyvek>
	<konyv id="B196443FO">
		<cim>Mesterséges intelligencia</cim>
		<kiadas>2005</kiadas>
		<kiado>Miskolci Egyetem</kiado>
		<szerzo>Szabó Gábor</szerzo>
		<abstract>absztakt</abstract>
	</konyv>
	<konyv id="B516751DI">
		<cim>C programozási nyelv alapjai</cim>
		<kiadas>1991</kiadas>
		<kiado>Szabó és társa Zrt.</kiado>
		<szerzo>Boglár Klára</szerzo>
		<szerzo>Kovács Tibor Elemér</szerzo>
	</konyv>
	<konyv id="B156349BI">
		<cim>Bash Script a gyakorlatban</cim>
		<kiadas>2001</kiadas>
		<kiado>Budapest Konyv kiado</kiado>
		<szerzo>Balogh Gabriella</szerzo>
	</konyv>
</konyvek>
